name: Restore Prod Backup to Dev

on:
  workflow_dispatch:
    inputs:
      backup_url:
        description: 'Full URL to the backup file (can include SAS token)'
        required: true
      target_database:
        description: 'Target database name in dev'
        required: true

jobs:
  restore:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run restore script
        shell: pwsh
        env:
          SQL_AUTH_USER: ${{ secrets.SQL_AUTH_USER }}
          SQL_AUTH_PASSWORD: ${{ secrets.SQL_AUTH_PASSWORD }}
        run: |
          $backupUrl = "${{ github.event.inputs.backup_url }}"
          $targetDb = "${{ github.event.inputs.target_database }}"
          $instance = "localhost" # change to your dev instance or provide as secret/variable
          Write-Host "Restoring $backupUrl -> $instance::$targetDb"
          .\scripts\restore-prod-to-dev.ps1 -BackupUrl $backupUrl -TargetSqlInstance $instance -TargetDatabaseName $targetDb -SqlAuthUser $env:SQL_AUTH_USER -SqlAuthPassword $env:SQL_AUTH_PASSWORD -ReplaceExisting
